version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Running pre-build tasks...
  build:
    commands:
      - echo Running build tasks...
      - npm install  # Run a build script (e.g., transpiling, bundling, etc.)
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running tests...
artifacts:
  files:
    - '**/*'   # Include all files in the project directory in the output artifact
  