version: 0.2
run-as: root
 
phases:
  pre_build:
    commands:
      - cd sample-nodejs-app
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com 
  build:
    commands:
      - docker build --cache-from $REPOSITORY_URI:$IMAGE_TAG -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"calculator-task","imageUri":"%s"}]' 381491838685.dkr.ecr.ap-south-1.amazonaws.com/calculator-nodejs-demo:latest > imagedefinitions.json 
artifacts:
  files: [imagedefinitions.json]
  discard-paths: yes